#!/usr/bin/env expect
set mac [lindex $argv 0]
set prompt "\\\[.*\\\]>"
set timeout 5
log_user 0

proc pair {address prompt} {
    expect *
    send_user "Pairing device '$address'"
    send "pair $address\r"

    expect {
        -re "Pairing successful" {
            send "trust $address\r"

            expect -re "$address trust succeeded"
            send_user "Connecting to device '$address'"
            send "connect $address\r"

            expect -re $prompt { return true }
        }
        -re "Failed to pair" { return false }
    }
}

# Taken from https://github.com/bluez/bluez/issues/692#issuecomment-2813186567
proc wait_for_device {address} {
    send_user "\nWaiting for device\n"
    expect *
    send "devices\r"
    expect {
        timeout { wait_for_device $address }
        -re "Device $address"
    }
}

spawn bluetoothctl

expect *
send "info $mac\r"

expect {
    -re "Device $mac not available" {
        send_user "Device '$mac' unavailable, please make sure it's discoverable"

        send "scan on\r"
        wait_for_device $mac

        expect {
            timeout { pair $mac $prompt }
            -re "Pairing successful"
        }
    }
    -re "Connected: yes" {
        send_user "Headphones already connected, exiting..."
        send "quit\r"
    }
    -re "Paired: no" { pair $mac $prompt }
    -re "Connected: no" {
        send_user "Connecting to device '$mac'"
        send "connect $mac\r"

        expect -re $prompt
        send "quit\r"
    }
}
